// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxgWpF326wNOtSvASeyU4Nx5r9Vw36UBw',
    appId: '1:319434175258:web:399fb3cbd152099dda32a3',
    messagingSenderId: '319434175258',
    projectId: 'student-management-e5238',
    authDomain: 'student-management-e5238.firebaseapp.com',
    storageBucket: 'student-management-e5238.appspot.com',
    measurementId: 'G-L9GW7G4VN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA76O9UvtU-yhp4RWFBa67p_wNU8jjuFWI',
    appId: '1:319434175258:android:8637377fe18f0258da32a3',
    messagingSenderId: '319434175258',
    projectId: 'student-management-e5238',
    storageBucket: 'student-management-e5238.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNTPLgBwGOGF3j4YxBJmEGPkpcSj06AXU',
    appId: '1:319434175258:ios:967c15fe58516250da32a3',
    messagingSenderId: '319434175258',
    projectId: 'student-management-e5238',
    storageBucket: 'student-management-e5238.appspot.com',
    iosBundleId: 'com.example.studentManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNTPLgBwGOGF3j4YxBJmEGPkpcSj06AXU',
    appId: '1:319434175258:ios:cddc23e36ef13ff9da32a3',
    messagingSenderId: '319434175258',
    projectId: 'student-management-e5238',
    storageBucket: 'student-management-e5238.appspot.com',
    iosBundleId: 'com.example.studentManagement.RunnerTests',
  );
}
